name: 'Close stale issues and pull requests'

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  stale:
    name: ðŸ§¹ Clean up stale issues and PRs
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: ðŸš€ Run stale and close
        uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-issue-stale: 30
          days-before-issue-close: 7
          days-before-pr-stale: 30
          days-before-pr-close: 10
          remove-stale-when-updated: true
          stale-issue-label: 'stale'
          exempt-issue-labels: 'no-stale,help-wanted'
          stale-issue-message: >
            There hasn't been any activity on this issue recently, and in order
            to prioritize active issues, it will be marked as stale.

            Please make sure to update to the latest version and
            check if that solves the issue. Let us know if that works for you
            by leaving a ðŸ‘

            Because this issue is marked as stale, it will be closed and locked
            in 7 days if no further activity occurs.

            Thank you for your contributions!
          close-issue-message: >
            This issue was closed because it has been stalled for 7 days with no activity.

            If you encounter this same issue, please open a new issue and refer
            to this closed one.
          stale-pr-label: 'stale'
          exempt-pr-labels: 'no-stale'
          stale-pr-message: >
            There hasn't been any activity on this pull request recently, and in
            order to prioritize active work, it has been marked as stale.

            This pull request will be closed and locked in 7 days if no further activity
            occurs.

            Thank you for your contributions!
          close-pr-message: >
            This pull request was closed because it has been stalled for 10 days with no activity.
